#
# DO NOT EDIT THIS FILE DIRECTLY - UNLESS YOU KNOW WHAT YOU ARE DOING
#

user node[:kafka][:user] do
  action :create
  supports :manage_home => true
  home "/home/#{node[:kafka][:user]}"
  shell "/bin/bash"
  not_if "getent passwd #{node[:kafka]['user']}"
end

group node[:kafka][:group] do
  action :modify
  members ["#{node[:kafka][:user]}"]
  append true
end


# See ark resource here: https://github.com/burtlo/ark
# It will: fetch it to to /var/cache/chef/
# unpack it to the default path (/usr/local/XXX-1.2.3)
# create a symlink for :home_dir (/usr/local/XXX) 
# add /user/local/XXX/bin to the enviroment PATH variable
#  ark 'kkafka' do
#    url node[:kkafka][:url]
#    version node[:kkafka][:version]
#    path node[:kkafka][:version_dir]
#    home_dir node[:kkafka][:home_dir]
#    
#    append_env_path true
#    owner node[:kkafka][:user]
#  end

# bash "experiment_install_bash" do
#     user "root"
#     code <<-EOF
# Do something here...
# touch #{node[:kkafka][:version_dir]}/.installed
# EOF
#   not_if { ::File.exists?( "#{node[:kkafka][:version_dir]}/.installed" ) }
# end

#my_private_ip= my_private_ip()
#my_public_ip= my_public_ip()



# Pre-Experiment Code


# Configuration Files

include_recipe 'kafka::_defaults'
include_recipe 'kafka::_setup'

kafka_download kafka_local_download_path do
  source kafka_download_uri(kafka_tar_gz)
  checksum node.kafka.checksum
  md5_checksum node.kafka.md5_checksum
  not_if { kafka_installed? }
end

execute 'extract-kafka' do
  cwd node.kafka.build_dir
  command <<-EOH.gsub(/^\s+/, '')
    tar zxf #{kafka_local_download_path} && \
    chown -R #{node.kafka.user}:#{node.kafka.group} #{node.kafka.build_dir}
  EOH
  not_if { kafka_installed? }
end

kafka_install node.kafka.version_install_dir do
  from kafka_target_path
  not_if { kafka_installed? }
end
